import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner.js';
import Card from '../components/card.js';
import styles from '../styles/Home.module.css'
import coffeeStoresData from '../data/coffee-stores.json';
import axios from 'axios';


export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores:coffeeStoresData,
    }
  }
}

export default function Home(props) {
  function bannerButtonClickHandler() {
    console.log("banner button");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" bannerButtonOnClick={bannerButtonClickHandler} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt='hero-image' />
        </div>

        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(store => {
                return (
                  <Card
                    key={store.id}
                    name={store.name}
                    imageUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`}
                  />
                )
              })}
            </div>
          </>
        )}

      </main>
    </div>
  )
}
